'use client'
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Script id="quiz-form" src="https://cdn101-om162-client.phonexa.com/form/run.php?p=E84F20F55F744C9C93B0597EEB4F68C7" strategy="afterInteractive" />
      </body>
    </html>
  );
}
